name: detnet
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.8

  - cudatoolkit=10.1
  - pytorch=1.7.0
  - torchvision

#  - opencv
  - cython
  - scipy
  - scikit-learn
  #  - matplotlib
  - tqdm
  - pandas
  - pyyaml
  - scikit-image
  - shapely
  - seaborn

  - pip
  - pip:
      - opencv-python
      - tensorboardX
#      - pillow-simd
      - future
      - mlflow
      - pycocotools

      - git+https://github.com/NVIDIA/apex.git@1f2aa9156547377a023932a1512752c392d9bbdf
      #    - torchsummary
      - pretrainedmodels
      - efficientnet-pytorch==0.6.3
      #    - detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/index.html
      - https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/detectron2-0.3%2Bcu101-cp38-cp38-linux_x86_64.whl
      - git+https://github.com/zhanghang1989/ResNeSt.git@11eb547225c6b98bdf6cab774fb58dffc53362b1
      #      - mmcv-full==1.2.5 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html
#      - https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/mmcv_full-1.2.5-cp38-cp38-manylinux1_x86_64.whl
#      - git+https://github.com/xuyuan/mmdetection.git@2.8.0
      - https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/mmcv_full-1.3.4-cp38-cp38-manylinux1_x86_64.whl
      - mmdet==2.11.0
